### ISSUE TITLE
no css when i use the component

### ISSUE THREAD

**Issue by YingXiaoMing** [juxant/BlazorTransfer#1]

**Comment by jusaan** [comment]
In .NET 5, you need to add the following line in **_host.cshtml** (Server Side) or **index.html** (WebAssembly)

`<link href="{ASSEMBLY NAME}.styles.css" rel="stylesheet">`

Source: https://docs.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-5.0#css-isolation-bundling

In .NET Core 3.1 or lower, download **1.0.6** version and follow this instructions
https://github.com/juxant/BlazorTransfer/blob/5d3efaa47d12985ff88a2fc56e1ba6521569b436/README.md
